# Generated by Django 6.0.1 on 2026-01-29 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset_bibliotecary', '0001_initial'),
        ('viewset_books', '0002_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bibliotecary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_loans', to='viewset_bibliotecary.bibliotecary'),
        ),
    ]
